// Date: 2014-04-09 10:08:51
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package me.uk.domos.holidaycraft.model;

import me.uk.domos.holidaycraft.tileentity.TileEntityRibbon;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.world.World;

public class ModelRibbon extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
  
  public ModelRibbon()
  {
    textureWidth = 32;
    textureHeight = 32;
    
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 4, 1, 4);
      Shape1.setRotationPoint(-2F, 8F, -2F);
      Shape1.setTextureSize(32, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      
    	  Shape2 = new ModelRenderer(this, -1, 5);
    	  Shape2.addBox(0F, 0F, 0F, 6, 1, 4);
    	  Shape2.setRotationPoint(2F, 8F, -2F);
    	  Shape2.setTextureSize(32, 32);
    	  Shape2.mirror = true;
    	  setRotation(Shape2, 0F, 0F, 0F);
      
    	  Shape3 = new ModelRenderer(this, 0, 24);
    	  Shape3.addBox(0F, 0F, 0F, 6, 1, 4);
    	  Shape3.setRotationPoint(-8F, 8F, -2F);
    	  Shape3.setTextureSize(32, 32);
    	  Shape3.mirror = true;
    	  setRotation(Shape3, 0F, 0F, 0F);
      
    	  Shape4 = new ModelRenderer(this, 0, 10);
    	  Shape4.addBox(0F, 0F, 0F, 4, 1, 6);
    	  Shape4.setRotationPoint(-2F, 8F, 2F);
    	  Shape4.setTextureSize(32, 32);
    	  Shape4.mirror = true;
    	  setRotation(Shape4, 0F, 0F, 0F);
      
    	  Shape5 = new ModelRenderer(this, 0, 17);
    	  Shape5.addBox(0F, 0F, 0F, 4, 1, 6);
    	  Shape5.setRotationPoint(-2F, 8F, -8F);
    	  Shape5.setTextureSize(32, 32);
    	  Shape5.mirror = true;
    	  setRotation(Shape5, 0F, 0F, 0F);
  }
  
  public void render(int dip, boolean north, boolean south, boolean east, boolean west, Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    float dipfloat = dip/16f;
    Shape1.offsetY = dipfloat;
    Shape2.offsetY = dipfloat;
    Shape3.offsetY = dipfloat;
    Shape4.offsetY = dipfloat;
    Shape5.offsetY = dipfloat;
    Shape1.render(f5);
    if (west){Shape2.render(f5);}
  	if (east){Shape3.render(f5);}
    if (south){Shape4.render(f5);}
    if (north){Shape5.render(f5);}
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
